
package com.amel_e;


import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class GCustomerHome extends javax.swing.JFrame {

    /**
     * Creates new form GCustomerHomer
     */
    Manager m;

    public GCustomerHome() {
        initComponents();
        m = new Manager();
        Manager.fillFile();
        Manager.empthyList();
        Manager.fillList();
        lbl_name.setText(Manager.getCustomer().get(Manager.getIndex()).name+" "+Manager.getCustomer().get(Manager.getIndex()).surname);
        lbl_adress.setText(Manager.getCustomer().get(Manager.getIndex()).getAddress());
        lbl_account.setText(Manager.getCustomer().get(Manager.getIndex()).getAccount());
        pnl_deposit.setVisible(false);
    }

    public static JLabel getLbl_account() {
        return lbl_account;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        pnl_customer = new javax.swing.JPanel();
        lbl_account = new javax.swing.JLabel();
        lbl_adress = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        pnl_deposit = new javax.swing.JPanel();
        Jlbll = new javax.swing.JLabel();
        tf_card_number = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tf_amount = new javax.swing.JTextField();
        btn_charge = new javax.swing.JButton();
        pnl_parayatır = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pnl_order = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pnl_map = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_message = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_customer.setBackground(new java.awt.Color(255, 255, 255));
        pnl_customer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_account.setBackground(new java.awt.Color(45, 118, 232));
        lbl_account.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lbl_account.setForeground(new java.awt.Color(45, 118, 232));
        lbl_account.setText("money");
        pnl_customer.add(lbl_account, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 440, 40));

        lbl_adress.setBackground(new java.awt.Color(45, 118, 232));
        lbl_adress.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lbl_adress.setForeground(new java.awt.Color(45, 118, 232));
        lbl_adress.setText("adress");
        pnl_customer.add(lbl_adress, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 260, 40));

        lbl_name.setBackground(new java.awt.Color(45, 118, 232));
        lbl_name.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lbl_name.setForeground(new java.awt.Color(45, 118, 232));
        lbl_name.setText("name");
        lbl_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_nameMouseClicked(evt);
            }
        });
        pnl_customer.add(lbl_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 450, 40));

        pnl_deposit.setBackground(new java.awt.Color(255, 255, 255));
        pnl_deposit.setForeground(new java.awt.Color(255, 255, 255));

        Jlbll.setFont(new java.awt.Font("Verdana", 2, 24)); // NOI18N
        Jlbll.setForeground(new java.awt.Color(45, 118, 232));
        Jlbll.setText("Amount: ");

        tf_card_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_card_numberActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(45, 118, 232));
        jLabel1.setText("Card Number: ");

        btn_charge.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_charge.setText("DONE");
        btn_charge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chargeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_depositLayout = new javax.swing.GroupLayout(pnl_deposit);
        pnl_deposit.setLayout(pnl_depositLayout);
        pnl_depositLayout.setHorizontalGroup(
            pnl_depositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_depositLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_depositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(Jlbll))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_depositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_card_number, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnl_depositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_depositLayout.createSequentialGroup()
                    .addContainerGap(422, Short.MAX_VALUE)
                    .addComponent(btn_charge)
                    .addGap(37, 37, 37)))
        );
        pnl_depositLayout.setVerticalGroup(
            pnl_depositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_depositLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnl_depositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jlbll, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_depositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_card_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(pnl_depositLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_depositLayout.createSequentialGroup()
                    .addContainerGap(61, Short.MAX_VALUE)
                    .addComponent(btn_charge, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(9, 9, 9)))
        );

        pnl_customer.add(pnl_deposit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 550, 110));

        pnl_parayatır.setPreferredSize(new java.awt.Dimension(90, 120));
        pnl_parayatır.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_parayatırMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_parayatırMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_parayatırMouseEntered(evt);
            }
        });
        pnl_parayatır.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/amel_e/icons8-deposit-64.png"))); // NOI18N
        pnl_parayatır.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("DEPOSIT");
        pnl_parayatır.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        pnl_customer.add(pnl_parayatır, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, 100, -1));

        pnl_order.setMinimumSize(new java.awt.Dimension(90, 120));
        pnl_order.setPreferredSize(new java.awt.Dimension(90, 120));
        pnl_order.setRequestFocusEnabled(false);
        pnl_order.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_orderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_orderMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_orderMousePressed(evt);
            }
        });
        pnl_order.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/amel_e/icons8-purchase-order-80.png"))); // NOI18N
        pnl_order.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("ORDER");
        pnl_order.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        pnl_customer.add(pnl_order, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 100, -1));

        pnl_map.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_mapMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_mapMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnl_mapMousePressed(evt);
            }
        });
        pnl_map.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/amel_e/icons8-map-marker-50.png"))); // NOI18N
        pnl_map.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 70));

        jLabel4.setBackground(new java.awt.Color(14, 38, 232));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("MAP");
        pnl_map.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 60, 30));

        pnl_customer.add(pnl_map, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 100, 120));

        btn_back.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        pnl_customer.add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(691, 340, 90, 40));

        jPanel2.add(pnl_customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 790, 410));

        jPanel3.setBackground(new java.awt.Color(45, 118, 232));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("CUSTOMER");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 340, 110));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("amel-e");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 150, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/amel_e/ameleee.jpg"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 180));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 580));
        getContentPane().add(lbl_message, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 550, 460, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_nameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_nameMouseClicked

    private void tf_card_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_card_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_card_numberActionPerformed

    private void pnl_parayatırMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_parayatırMouseClicked
        pnl_deposit.setVisible(true);
        tf_amount.setText(null);
        tf_card_number.setText(null);
    }//GEN-LAST:event_pnl_parayatırMouseClicked

    private void pnl_mapMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_mapMousePressed
         GLogin.gMap.setVisible(true);
    }//GEN-LAST:event_pnl_mapMousePressed

    private void pnl_orderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_orderMousePressed
        GLogin.gOrder.setVisible(true);
        this.setVisible(false);
        //sor
        Manager.fillFile();
    }//GEN-LAST:event_pnl_orderMousePressed

    private void pnl_mapMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_mapMouseEntered
        setColor(pnl_map);
        
    }//GEN-LAST:event_pnl_mapMouseEntered

    private void pnl_mapMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_mapMouseExited
        resetColor(pnl_map);
    }//GEN-LAST:event_pnl_mapMouseExited

    private void pnl_orderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_orderMouseEntered
        setColor(pnl_order);
    }//GEN-LAST:event_pnl_orderMouseEntered

    private void pnl_orderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_orderMouseExited
        resetColor(pnl_order);
    }//GEN-LAST:event_pnl_orderMouseExited

    private void pnl_parayatırMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_parayatırMouseEntered
        setColor(pnl_parayatır);
    }//GEN-LAST:event_pnl_parayatırMouseEntered

    private void pnl_parayatırMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_parayatırMouseExited
       resetColor(pnl_parayatır);
    }//GEN-LAST:event_pnl_parayatırMouseExited

    private void btn_chargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chargeActionPerformed
       // Tf' e girilen miktarı kullanıcının hesabına ekliyor.
        // fillfile methodu kullanıcı verileni dosyaya atıyor.
        //empyhtylist methodu müşterileri tuttuğumuz arraylisti boşaltıyor.
        //filllist methodu boşalttığımız arrayliste dosyaya yazarak güncelleğimiz verileri alıyor.
        //Bu sayede anlık olarak verilerimizi güncellemiş oluyoruz.
        
        if (tf_amount.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter AMOUNT that you want to add your account!");
        }else if(tf_card_number.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please enter your CARD NUMBER!");
        }else{
      
        double after = Double.parseDouble(tf_amount.getText());
        String[] control;
        control = lbl_account.getText().split(" ");
        double before = Double.parseDouble(control[0]);

        double res = after + before;
      
        String result = String.valueOf(res);
        Manager.getCustomer().get(Manager.getIndex()).setAccount(result);
        lbl_account.setText(Manager.getCustomer().get(Manager.getIndex()).getAccount() + " TL");
        
        pnl_deposit.setVisible(false);
        //Manager.fillFile();
        Manager.fillFile();
        Manager.empthyList();
        Manager.fillList();
        }
    }//GEN-LAST:event_btn_chargeActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        GOrder.total = 0;
        this.setVisible(false);
        new GLogin().setVisible(true);
    }//GEN-LAST:event_btn_backActionPerformed

    public void setColor(JPanel panel){
        panel.setBackground(new java.awt.Color(156,156,156));
    }
    
    public void resetColor(JPanel panel){
        panel.setBackground(new java.awt.Color(240,240,240));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GCustomerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GCustomerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GCustomerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GCustomerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GCustomerHome().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jlbll;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_charge;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private static javax.swing.JLabel lbl_account;
    private javax.swing.JLabel lbl_adress;
    private javax.swing.JLabel lbl_message;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JPanel pnl_customer;
    private javax.swing.JPanel pnl_deposit;
    private javax.swing.JPanel pnl_map;
    private javax.swing.JPanel pnl_order;
    private javax.swing.JPanel pnl_parayatır;
    private javax.swing.JTextField tf_amount;
    private javax.swing.JTextField tf_card_number;
    // End of variables declaration//GEN-END:variables
}
