/*
    Search kontrol
*/
package com.amel_e;

import static com.amel_e.GOrder.tbl_food;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class GManagerHome extends javax.swing.JFrame {

    /**
     * Creates new form GManagerHome
     */
    public GManagerHome() {

        initComponents();
        tbl_product.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 18));
        tbl_product.getTableHeader().setOpaque(false);
        tbl_product.getTableHeader().setBackground(Color.BLACK);//???
        tbl_product.getTableHeader().setForeground(Color.BLACK);
        tbl_product.setRowHeight(25);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        lbl_message = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btn_search = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_customerInfo = new javax.swing.JTextArea();
        pnl_addProduct = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_productName = new javax.swing.JTextField();
        tf_price = new javax.swing.JTextField();
        cb_category = new javax.swing.JComboBox<>();
        btn_add = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_product = new javax.swing.JTable();
        btn_remove = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        tf_namesurname = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GManagerHome");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 465, 471, -1));
        getContentPane().add(lbl_message, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 458, 311, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(45, 118, 232));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 60)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ADMIN");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 252, 110));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("amel-e");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 150, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/amel_e/ameleee.jpg"))); // NOI18N
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 0, 220, 200));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 200));

        btn_search.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_search.setText("SEARCH");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });
        btn_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_searchKeyPressed(evt);
            }
        });
        jPanel1.add(btn_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 320, 120, 40));

        ta_customerInfo.setEditable(false);
        ta_customerInfo.setColumns(20);
        ta_customerInfo.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        ta_customerInfo.setRows(5);
        jScrollPane1.setViewportView(ta_customerInfo);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 430, 530, 182));

        pnl_addProduct.setForeground(new java.awt.Color(240, 240, 240));
        pnl_addProduct.setToolTipText("");

        jLabel4.setBackground(new java.awt.Color(45, 118, 232));
        jLabel4.setFont(new java.awt.Font("Verdana", 2, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(45, 118, 232));
        jLabel4.setText("Product Name:");

        jLabel5.setFont(new java.awt.Font("Verdana", 2, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(45, 118, 232));
        jLabel5.setText("Category: ");

        jLabel6.setFont(new java.awt.Font("Verdana", 2, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(45, 118, 232));
        jLabel6.setText("Price:");

        cb_category.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cb_category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Food", "Drink", "Others" }));
        cb_category.setSelectedIndex(-1);

        btn_add.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_add.setText("ADD");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        tbl_product.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Category", "Price"
            }
        ));
        tbl_product.setFocusable(false);
        tbl_product.setSelectionBackground(new java.awt.Color(42, 118, 232));
        tbl_product.setShowVerticalLines(false);
        tbl_product.getTableHeader().setReorderingAllowed(false);
        tbl_product.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_productMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_product);

        btn_remove.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_remove.setText("REMOVE");
        btn_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeActionPerformed(evt);
            }
        });

        btn_update.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_update.setText("UPDATE");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Products");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_addProductLayout = new javax.swing.GroupLayout(pnl_addProduct);
        pnl_addProduct.setLayout(pnl_addProductLayout);
        pnl_addProductLayout.setHorizontalGroup(
            pnl_addProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_addProductLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pnl_addProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnl_addProductLayout.createSequentialGroup()
                        .addGroup(pnl_addProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_addProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_price, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_category, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_productName, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(81, 81, 81))
                    .addGroup(pnl_addProductLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)))
                .addGroup(pnl_addProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(pnl_addProductLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_addProductLayout.setVerticalGroup(
            pnl_addProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_addProductLayout.createSequentialGroup()
                .addGroup(pnl_addProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_addProductLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(pnl_addProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tf_productName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_add))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnl_addProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(btn_update))
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_addProductLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(pnl_addProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(btn_remove)
                    .addComponent(tf_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(pnl_addProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 640, 560));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/amel_e/icons8-search-48.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 300, 50, 50));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 350, 360, 10));

        tf_namesurname.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        tf_namesurname.setBorder(null);
        jPanel1.add(tf_namesurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 330, 370, 20));

        jButton2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 680, 90, 30));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(48, 112, 232));
        jLabel1.setText("Customer Name and Surname");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 270, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 760));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeActionPerformed
        //Adminin ürün ekledikten sonra ordan kaldırması için yazılmış method
        //Belki bizim order framinden ürün silmek için kullanılabilir
        FileOutputStream fos = null;
        BufferedReader reader;
        String line = "";
        String res = "";
        String[] control;

        if (tf_productName.getText().equals(null) || cb_category.getSelectedIndex()==-1 || tf_price.getText().equals(null)) {
            JOptionPane.showMessageDialog(this, "Please select a product for REMOVE product from list! ");
        }
        
        else{
            
        
        try {
            reader = new BufferedReader(new FileReader("/home/nbt/Documents/Amel_e/src/com/amel_e/Product.txt"));
            line = reader.readLine();
            while (line!=null){

                if((tf_productName.getText() + " " + cb_category.getSelectedItem().toString() + " " + tf_price.getText()).equals(line)){
                   
                    line = reader.readLine();
                    if(line == null)
                        continue;
                    
                }
      
                res += line;
                res += "\n";
                line = reader.readLine();
            }
            reader.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
        byte [] arr = res.getBytes();
        try {
            fos = new FileOutputStream("/home/nbt/Documents/Amel_e/src/com/amel_e/Product.txt", false);
            fos.write(arr);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(GManagerHome.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(GManagerHome.class.getName()).log(Level.SEVERE, null, ex);
        }
 
        DefaultTableModel model = (DefaultTableModel) tbl_product.getModel();
        
        int secili_row = tbl_product.getSelectedRow();
           
            if (secili_row!=-1) {
                 model.removeRow(secili_row);
            }
           
        
        tf_productName.setText(null);
        cb_category.setSelectedIndex(-1);
        tf_price.setText(null);
        }
        
    }//GEN-LAST:event_btn_removeActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        
        FileOutputStream fos = null;
        BufferedReader reader;
        String line = "";
        String res = "";
        String[] control;

        if (tf_productName.getText().equals(null) || cb_category.getSelectedIndex()==-1 || tf_price.getText().equals(null)) {
            JOptionPane.showMessageDialog(this, "Please select a product update product PRICE! ");
        }
        else{

        try {
            reader = new BufferedReader(new FileReader("/home/nbt/Documents/Amel_e/src/com/amel_e/Product.txt"));
            line = reader.readLine();
            while (line != null){

                if(line.split(" ")[0].equals(tf_productName.getText()) && line.split(" ")[1].equals(cb_category.getSelectedItem().toString())){
                   line = tf_productName.getText() + " " + cb_category.getSelectedItem().toString() + " " + tf_price.getText();
                    
                }
                    
                res += line;
                res += "\n";
                line = reader.readLine();
            }
            reader.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
        byte [] arr = res.getBytes();
        try {
            fos = new FileOutputStream("/home/nbt/Documents/Amel_e/src/com/amel_e/Product.txt", false);
            fos.write(arr);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(GManagerHome.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(GManagerHome.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        DefaultTableModel model = (DefaultTableModel) tbl_product.getModel();
        
        int secili_row = tbl_product.getSelectedRow();
        
        
        if(secili_row!=-1) {
            
            //model.setValueAt(tf_productName.getText(),secili_row,0);
           
            //model.setValueAt(cb_category.getSelectedItem().toString(),secili_row,1);
            
            model.setValueAt(tf_price.getText(),secili_row,2);
            tbl_product.clearSelection();
          
            
        }
        tf_price.setText(null);
        tf_productName.setText(null);
        cb_category.setSelectedIndex(-1);
        }
        
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        lbl_message.setText("");

        DefaultTableModel model = (DefaultTableModel) tbl_product.getModel();
   
        if (tf_productName.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter product name!");
        } else {
            Object[] eklenecek = {tf_productName.getText(), cb_category.getSelectedItem().toString(), tf_price.getText()};

            String line = "";
            FileOutputStream fos = null;
            line += tf_productName.getText() + " " + cb_category.getSelectedItem().toString() + " "
                    + tf_price.getText() + "\n";
            byte[] info = line.getBytes();
            try {
                fos = new FileOutputStream("/home/nbt/Documents/Amel_e/src/com/amel_e/Product.txt", true);
                fos.write(info);

            } catch (FileNotFoundException ex) {
                Logger.getLogger(Manager.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Manager.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    fos.close();
                } catch (IOException ex) {
                    Logger.getLogger(Manager.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            model.addRow(eklenecek);
            GOrder.fillProducts();
            
            tf_productName.setText(null);
            tf_price.setText(null);
            cb_category.setSelectedIndex(-1);
        }

    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        //Adminin müşteri isim soyisim kullanarak müşterinin sipariş geçmişini yazdırdığı method.
        //System classtan
        if (tf_namesurname.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter customer name and surname for search customer!");
        }else{
            Manager.getCustomer().get(Manager.getIndex()).getS1().search();
        }
            
    }//GEN-LAST:event_btn_searchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new GupdatedTable().setVisible(true);
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    this.setVisible(false);
     new GLogin().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_searchKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
             Manager.getCustomer().get(Manager.getIndex()).getS1().search();
    }//GEN-LAST:event_btn_searchKeyPressed

    private void tbl_productMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_productMouseClicked

        DefaultTableModel model = (DefaultTableModel) tbl_product.getModel();

        int secili_row = tbl_product.getSelectedRow();

        tf_productName.setText(model.getValueAt(secili_row, 0).toString());
        cb_category.setSelectedItem(model.getValueAt(secili_row, 1).toString());
        tf_price.setText(model.getValueAt(secili_row, 2).toString());
    }//GEN-LAST:event_tbl_productMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GManagerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GManagerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GManagerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GManagerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GManagerHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_remove;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_update;
    public static javax.swing.JComboBox<String> cb_category;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_message;
    private javax.swing.JPanel pnl_addProduct;
    public static javax.swing.JTextArea ta_customerInfo;
    private javax.swing.JTable tbl_product;
    public static javax.swing.JTextField tf_namesurname;
    public static javax.swing.JTextField tf_price;
    public static javax.swing.JTextField tf_productName;
    // End of variables declaration//GEN-END:variables
}
