package com.amel_e;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

public class GMap extends javax.swing.JFrame {

    /**
     * Creates new form GMap
     */
    ImageIcon center = new ImageIcon(getClass().getResource("center.jpg"));
    ImageIcon build1 = new ImageIcon(getClass().getResource("build1.jpg"));
    ImageIcon build2 = new ImageIcon(getClass().getResource("build2.jpg"));
    ImageIcon build3 = new ImageIcon(getClass().getResource("build3.jpg"));
    ImageIcon build4 = new ImageIcon(getClass().getResource("build4.jpg"));
    ImageIcon build5 = new ImageIcon(getClass().getResource("build5.jpg"));
    ImageIcon build6 = new ImageIcon(getClass().getResource("build6.jpg"));
    ImageIcon build7 = new ImageIcon(getClass().getResource("build7.jpg"));
    ImageIcon build8 = new ImageIcon(getClass().getResource("build8.jpg"));
    ImageIcon market = new ImageIcon(getClass().getResource("market.jpg"));

    public GMap() {

        initComponents();
        ImageIcon cen = new ImageIcon(center.getImage().getScaledInstance(lbl_center.getHeight(), lbl_center.getWidth(), Image.SCALE_SMOOTH));
        ImageIcon b1 = new ImageIcon(build1.getImage().getScaledInstance(lbl_build1.getHeight(), lbl_build1.getWidth(), Image.SCALE_SMOOTH));
        ImageIcon b2 = new ImageIcon(build2.getImage().getScaledInstance(lbl_build8.getHeight(), lbl_build8.getWidth(), Image.SCALE_SMOOTH));
        ImageIcon b3 = new ImageIcon(build3.getImage().getScaledInstance(lbl_build4.getHeight(), lbl_build4.getWidth(), Image.SCALE_SMOOTH));
        ImageIcon b4 = new ImageIcon(build4.getImage().getScaledInstance(lbl_build3.getHeight(), lbl_build3.getWidth(), Image.SCALE_SMOOTH));
        ImageIcon b5 = new ImageIcon(build5.getImage().getScaledInstance(lbl_build7.getHeight(), lbl_build7.getWidth(), Image.SCALE_SMOOTH));
        ImageIcon b6 = new ImageIcon(build6.getImage().getScaledInstance(lbl_build2.getHeight(), lbl_build2.getWidth(), Image.SCALE_SMOOTH));
        ImageIcon b7 = new ImageIcon(build7.getImage().getScaledInstance(lbl_build5.getHeight(), lbl_build5.getWidth(), Image.SCALE_SMOOTH));
        ImageIcon b8 = new ImageIcon(build8.getImage().getScaledInstance(lbl_build6.getHeight(), lbl_build6.getWidth(), Image.SCALE_SMOOTH));
        ImageIcon mar = new ImageIcon(market.getImage().getScaledInstance(lbl_market.getHeight(), lbl_market.getWidth(), Image.SCALE_SMOOTH));

        lbl_center.setIcon(cen);
        lbl_build1.setIcon(b1);
        lbl_build2.setIcon(b2);
        lbl_build3.setIcon(b3);
        lbl_build4.setIcon(b4);
        lbl_build5.setIcon(b5);
        lbl_build6.setIcon(b6);
        lbl_build7.setIcon(b7);
        lbl_build8.setIcon(b8);
        lbl_market.setIcon(mar);

        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

    }

    public static JLabel getLbl_kurye() {
        return lbl_kurye;
    }

    public static JLabel getLbl_kurye1() {
        return lbl_kurye1;
    }

    public static JLabel getLbl_kurye2() {
        return lbl_kurye2;
    }

    public static JLabel getLbl_kurye3() {
        return lbl_kurye3;
    }

    public static JLabel getLbl_build1() {
        return lbl_build1;
    }

    public static JLabel getLbl_build2() {
        return lbl_build2;
    }

    public static JLabel getLbl_build3() {
        return lbl_build3;
    }

    public static JLabel getLbl_build4() {
        return lbl_build4;
    }

    public static JLabel getLbl_build5() {
        return lbl_build5;
    }

    public static JLabel getLbl_build6() {
        return lbl_build6;
    }

    public static JLabel getLbl_build7() {
        return lbl_build7;
    }

    public static JLabel getLbl_build8() {
        return lbl_build8;
    }

    public static JLabel getLbl_market() {
        return lbl_market;
    }

    public static JLabel getLbl_info1() {
        return lbl_info1;
    }

    public static JLabel getLbl_info2() {
        return lbl_info2;
    }

    public static JLabel getLbl_info3() {
        return lbl_info3;
    }

    public static JLabel getLbl_info4() {
        return lbl_info4;
    }

    public static JLabel getLbl_info5() {
        return lbl_info5;
    }

    public static JLabel getLbl_kurye4() {
        return lbl_kurye4;
    }

    public static JLabel getLbl_info6() {
        return lbl_info6;
    }

    public static JLabel getLbl_info7() {
        return lbl_info7;
    }

    public static JLabel getLbl_info8() {
        return lbl_info8;
    }

    public static JLabel getLbl_center() {
        return lbl_center;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_build6 = new javax.swing.JLabel();
        lbl_info2 = new javax.swing.JLabel();
        lbl_build1 = new javax.swing.JLabel();
        lbl_info4 = new javax.swing.JLabel();
        lbl_info1 = new javax.swing.JLabel();
        lbl_build8 = new javax.swing.JLabel();
        lbl_center = new javax.swing.JLabel();
        lbl_market = new javax.swing.JLabel();
        lbl_build5 = new javax.swing.JLabel();
        lbl_build4 = new javax.swing.JLabel();
        lbl_build2 = new javax.swing.JLabel();
        lbl_info3 = new javax.swing.JLabel();
        lbl_info8 = new javax.swing.JLabel();
        lbl_build7 = new javax.swing.JLabel();
        lbl_build3 = new javax.swing.JLabel();
        lbl_info5 = new javax.swing.JLabel();
        lbl_info7 = new javax.swing.JLabel();
        lbl_info6 = new javax.swing.JLabel();
        lbl_kurye = new javax.swing.JLabel();
        lbl_kurye1 = new javax.swing.JLabel();
        lbl_kurye2 = new javax.swing.JLabel();
        lbl_kurye3 = new javax.swing.JLabel();
        lbl_kurye4 = new javax.swing.JLabel();
        lbl_cen = new javax.swing.JLabel();
        lb_back3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("GMap"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1680, 1024));
        setResizable(false);
        getContentPane().setLayout(null);

        lbl_build6.setOpaque(true);
        getContentPane().add(lbl_build6);
        lbl_build6.setBounds(145, 824, 115, 110);

        lbl_info2.setBackground(new java.awt.Color(255, 204, 204));
        lbl_info2.setFont(new java.awt.Font("Viner Hand ITC", 3, 24)); // NOI18N
        lbl_info2.setText("APART 2");
        lbl_info2.setOpaque(true);
        getContentPane().add(lbl_info2);
        lbl_info2.setBounds(1430, 26, 130, 30);

        lbl_build1.setOpaque(true);
        getContentPane().add(lbl_build1);
        lbl_build1.setBounds(761, 113, 115, 110);

        lbl_info4.setBackground(new java.awt.Color(255, 204, 204));
        lbl_info4.setFont(new java.awt.Font("Viner Hand ITC", 3, 24)); // NOI18N
        lbl_info4.setText("APART 4");
        lbl_info4.setOpaque(true);
        getContentPane().add(lbl_info4);
        lbl_info4.setBounds(1470, 770, 115, 40);

        lbl_info1.setBackground(new java.awt.Color(255, 204, 204));
        lbl_info1.setFont(new java.awt.Font("Viner Hand ITC", 3, 24)); // NOI18N
        lbl_info1.setText("APART 1");
        lbl_info1.setOpaque(true);
        getContentPane().add(lbl_info1);
        lbl_info1.setBounds(760, 66, 115, 30);

        lbl_build8.setOpaque(true);
        getContentPane().add(lbl_build8);
        lbl_build8.setBounds(100, 120, 115, 110);

        lbl_center.setOpaque(true);
        getContentPane().add(lbl_center);
        lbl_center.setBounds(761, 516, 115, 110);

        lbl_market.setOpaque(true);
        getContentPane().add(lbl_market);
        lbl_market.setBounds(980, 560, 115, 110);

        lbl_build5.setOpaque(true);
        getContentPane().add(lbl_build5);
        lbl_build5.setBounds(845, 824, 115, 110);

        lbl_build4.setOpaque(true);
        getContentPane().add(lbl_build4);
        lbl_build4.setBounds(1470, 820, 115, 110);

        lbl_build2.setOpaque(true);
        getContentPane().add(lbl_build2);
        lbl_build2.setBounds(1430, 70, 115, 110);

        lbl_info3.setBackground(new java.awt.Color(255, 204, 204));
        lbl_info3.setFont(new java.awt.Font("Viner Hand ITC", 3, 24)); // NOI18N
        lbl_info3.setText("APART 3");
        lbl_info3.setOpaque(true);
        getContentPane().add(lbl_info3);
        lbl_info3.setBounds(1480, 396, 115, 30);

        lbl_info8.setBackground(new java.awt.Color(255, 204, 204));
        lbl_info8.setFont(new java.awt.Font("Viner Hand ITC", 3, 24)); // NOI18N
        lbl_info8.setText("APART 8");
        lbl_info8.setOpaque(true);
        getContentPane().add(lbl_info8);
        lbl_info8.setBounds(110, 66, 115, 40);

        lbl_build7.setOpaque(true);
        getContentPane().add(lbl_build7);
        lbl_build7.setBounds(110, 410, 115, 110);

        lbl_build3.setOpaque(true);
        getContentPane().add(lbl_build3);
        lbl_build3.setBounds(1480, 440, 115, 110);

        lbl_info5.setBackground(new java.awt.Color(255, 204, 204));
        lbl_info5.setFont(new java.awt.Font("Viner Hand ITC", 3, 24)); // NOI18N
        lbl_info5.setText("APART 5");
        lbl_info5.setOpaque(true);
        getContentPane().add(lbl_info5);
        lbl_info5.setBounds(840, 786, 115, 30);

        lbl_info7.setBackground(new java.awt.Color(255, 204, 204));
        lbl_info7.setFont(new java.awt.Font("Viner Hand ITC", 3, 24)); // NOI18N
        lbl_info7.setText("APART 7");
        lbl_info7.setOpaque(true);
        getContentPane().add(lbl_info7);
        lbl_info7.setBounds(110, 366, 115, 30);

        lbl_info6.setBackground(new java.awt.Color(255, 204, 204));
        lbl_info6.setFont(new java.awt.Font("Viner Hand ITC", 3, 24)); // NOI18N
        lbl_info6.setText("APART 6");
        lbl_info6.setOpaque(true);
        getContentPane().add(lbl_info6);
        lbl_info6.setBounds(140, 776, 115, 40);

        lbl_kurye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/amel_e/carry.png"))); // NOI18N
        getContentPane().add(lbl_kurye);
        lbl_kurye.setBounds(760, 470, 150, 34);

        lbl_kurye1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/amel_e/carry.png"))); // NOI18N
        getContentPane().add(lbl_kurye1);
        lbl_kurye1.setBounds(639, 590, 130, 34);

        lbl_kurye2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/amel_e/carry.png"))); // NOI18N
        getContentPane().add(lbl_kurye2);
        lbl_kurye2.setBounds(629, 540, 140, 34);

        lbl_kurye3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/amel_e/carry.png"))); // NOI18N
        getContentPane().add(lbl_kurye3);
        lbl_kurye3.setBounds(629, 490, 140, 34);

        lbl_kurye4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/amel_e/carry.png"))); // NOI18N
        getContentPane().add(lbl_kurye4);
        lbl_kurye4.setBounds(820, 470, 150, 34);

        lbl_cen.setBackground(new java.awt.Color(255, 204, 204));
        lbl_cen.setFont(new java.awt.Font("Viner Hand ITC", 3, 24)); // NOI18N
        lbl_cen.setText("CENTER");
        lbl_cen.setOpaque(true);
        getContentPane().add(lbl_cen);
        lbl_cen.setBounds(760, 626, 110, 30);

        lb_back3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/amel_e/map.png"))); // NOI18N
        lb_back3.setText("Center");
        getContentPane().add(lb_back3);
        lb_back3.setBounds(0, 0, 1680, 980);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GMap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GMap().setVisible(true);
                /* System.out.println("kurye 0: " + lbl_kurye.getX() + " " + lbl_kurye.getY());
                 System.out.println("kurye 1: " + lbl_kurye1.getX() + " " + lbl_kurye1.getY());
                 System.out.println("kurye 2: " + lbl_kurye2.getX() + " " + lbl_kurye2.getY());
                 System.out.println("kurye 3: " + lbl_kurye3.getX() + " " + lbl_kurye3.getY());
                 System.out.println("kurye 4: " + lbl_kurye4.getX() + " " + lbl_kurye4.getY());
                 System.out.println("center: " + lbl_center.getX() + " " + lbl_center.getY());*/
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lb_back3;
    private static javax.swing.JLabel lbl_build1;
    private static javax.swing.JLabel lbl_build2;
    private static javax.swing.JLabel lbl_build3;
    private static javax.swing.JLabel lbl_build4;
    private static javax.swing.JLabel lbl_build5;
    private static javax.swing.JLabel lbl_build6;
    private static javax.swing.JLabel lbl_build7;
    private static javax.swing.JLabel lbl_build8;
    private javax.swing.JLabel lbl_cen;
    private static javax.swing.JLabel lbl_center;
    private static javax.swing.JLabel lbl_info1;
    private static javax.swing.JLabel lbl_info2;
    private static javax.swing.JLabel lbl_info3;
    private static javax.swing.JLabel lbl_info4;
    private static javax.swing.JLabel lbl_info5;
    private static javax.swing.JLabel lbl_info6;
    private static javax.swing.JLabel lbl_info7;
    private static javax.swing.JLabel lbl_info8;
    private static javax.swing.JLabel lbl_kurye;
    private static javax.swing.JLabel lbl_kurye1;
    private static javax.swing.JLabel lbl_kurye2;
    private static javax.swing.JLabel lbl_kurye3;
    private static javax.swing.JLabel lbl_kurye4;
    private static javax.swing.JLabel lbl_market;
    // End of variables declaration//GEN-END:variables

}
